version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-front
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
