version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-front
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000"
    networks:
      - internal

networks:
  internal:
    external: true
